<?php

/**
 * Email_Quota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Kartaca
 * @subpackage Doctrine
 * @author     Roy Simkes <roy@kartaca.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Email_Quota extends BaseEmail_Quota
{

}