<?php
/**
 * This file is part of Kartaca Sample ZF Blog.
 *
 * Kartaca Sample ZF Blog is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca Sample ZF Blog is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca Sample ZF Blog.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @package
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 * @author     roysimkes
 */

//Now let's add my custom stylesheet
$this->headLink()->appendStylesheet($this->baseUrl() . "/style.css");

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>My Personal Zend Framework Blog</title>
    <!-- Blueprint css framework add on -->
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/print.css" type="text/css" media="print">
    <!--[if lt IE 8]>
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/ie.css" type="text/css" media="screen, projection">
    <![endif]-->
    <link rel="stylesheet" href="<?=$this->baseUrl()?>/blueprint/plugins/fancy-type/screen.css" type="text/css" media="screen, projection">

    <!-- And my custom style sheet -->
    <?php echo $this->headLink() ?>
</head>
<body>
    <div class="container">
        <h1><a href="<?=$this->baseUrl()?>">My Personal Zend Framework Blog</a></h1>
        <h2 class="alt">That's a sample blog application for Zend Framework.</h2>
        <hr />
        <?php if (Zend_Auth::getInstance()->getIdentity()) { ?>
            <span class="alt"><a href="<?=$this->baseUrl()?>/posts/update">Add New Post</a></span>
            <span class="alt"><a href="<?=$this->baseUrl()?>/user/logout">Logout</a></span>
        <?php } else { ?>
            <span class="alt"><a href="<?=$this->baseUrl()?>/user">Login To Add New Posts</a></span>
        <?php } ?>
        <br />
        <?php echo $this->layout()->content; ?>
        <div id="footer">
            <div class="promote alt">
                <a href="http://code.kartaca.com/zf-blog">Zend Framework Sample Blog</a>
            </div>
            <p>
                Proud to be a <a href="http://www.gnu.org/licenses/">GPL</a> software<br />
                <a href="http://www.kartaca.com">Kartaca</a>
            </p>
        </div>
    </div>
</body>
</html>