<style>

    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }

</style>
<center>
    <div id="welcome">
        <br />
        <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
        <h3>This is your project's main page</h3><br /><br />
        <div id="more-information">
            <br />
            <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /><br /><br />
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a> |
            <br />
            <a href="http://roysimkes.net/blog/2009/07/setting-up-a-zend-framework-project-from-scratch/">Creating A Sample Project</a>
        </div>
    </div>
</center>
