<?php
/**
 * This file is part of Kartaca Sample ZF Blog.
 *
 * Kartaca Sample ZF Blog is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca Sample ZF Blog is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca Sample ZF Blog.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @package
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 * @author     roysimkes
 */

foreach ($this->posts as $post) { ?>
    <div class="post">
        <!-- Linking with routes -->
        <h2><a href="<?=$this->baseUrl();?>/show/<?=$post->permalink?>"><?=$post->title?></a></h2>
        <!-- Linking without routes... -->
        <!--<h2><a href="<?=$this->baseUrl();?>/posts/show/permalink/<?=$post->permalink?>"><?=$post->title?></a></h2>-->
        <div class="body">
            <?=nl2br($post->body)?>
        </div>
    </div>
    <hr />
<?php } ?>