<?php
/**
 * This file is part of Kartaca Sample ZF Blog.
 *
 * Kartaca Sample ZF Blog is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Kartaca Sample ZF Blog is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Kartaca Sample ZF Blog.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   Kartaca
 * @package    
 * @copyright  Copyright (c) 2010 Kartaca (http://www.kartaca.com)
 * @license    http://www.gnu.org/licenses/ GPL
 * @author     roysimkes
 */
?>
<div class="post">
    <h2><?=$this->post->title?></h2>
    <div class="body">
        <?=$this->post->body?>
    </div>
    <hr />
    Comments for this blog (<?=$this->commentsCount?>)
    <br />
    <?php if ($this->commentsCount > 0) { ?>
        <div class="comments">
            <?php foreach ($this->comments as $cmt) { ?>
                <div class="comment">
                    <h4><?=$cmt->title?></h4>
                    <div class="author"><?=$cmt->commentator?></div>
                    <div class="body"><?=nl2br($cmt->body)?></div>
                </div>
            <?php } ?>
        </div>
    <?php } else { ?>
        There is no comments for this post yet. Be the first!
    <?php } ?>
    <?php $this->commentForm ?>
</div>